name       : flare-game
version    : 1.0
release    : 2
source     :
    - https://github.com/clintbellanger/flare-game/archive/v1.0.tar.gz : 5c8e9d72fcbe59f1861f79ac7b76ceffe3ec61d1df241c32d9133fe158fba4c1
license    :
    - GPL-3.0
    - CC-BY-SA-3.0
component  : games.rpg
summary    : Fantasy action RPG using the FLARE engine
description: |
    Flare is a a single-player 2D action RPG with fast-paced action and a dark fantasy style. It is
    built on the FLARE engine (Free/Libre Action Roleplaying Engine).

    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited
    using Tiled.
rundeps    :
    - flare-engine
setup      : |
    %cmake . -DDATADIR="share/flare"
install    : |
    %make_install
