name       : flare-game
version    : '1.12'
release    : 11
source     :
    - https://github.com/flareteam/flare-game/archive/refs/tags/v1.12.tar.gz : 19a909f2c6e0868baae823bb491e8840d5fb3e0454f00201de8da119772e5160
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.rpg
summary    : Fantasy action RPG using the FLARE engine
description: |
    Flare is a a single-player 2D action RPG with fast-paced action and a dark fantasy style. It is
    built on the FLARE engine (Free/Libre Action Roleplaying Engine).

    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited
    using Tiled.
rundeps    :
    - flare-engine
setup      : |
    %cmake_ninja -DDATADIR="share/flare"
build      : |
    %ninja_build
install    : |
    %ninja_install
