name       : flare-game
version    : 1.06
release    : 6
source     :
    - https://github.com/clintbellanger/flare-game/archive/v1.06.tar.gz : 5eb3d187bde7cd3a16a95ffd311dc05a6d8ff68d3ddbadf2d2fb8243b0145a53
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.rpg
summary    : Fantasy action RPG using the FLARE engine
description: |
    Flare is a a single-player 2D action RPG with fast-paced action and a dark fantasy style. It is
    built on the FLARE engine (Free/Libre Action Roleplaying Engine).

    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited
    using Tiled.
rundeps    :
    - flare-engine
setup      : |
    %cmake_ninja -DDATADIR="share/flare"
install    : |
    %ninja_install
