name       : flare-game
version    : 1.09.01
release    : 8
source     :
    - https://github.com/flareteam/flare-game/archive/v1.09.01.tar.gz : 47d48bc049e9f4facc83bc36e0e7d4c8d02e09000af64ebb2d76efc68ff0d004
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.rpg
summary    : Fantasy action RPG using the FLARE engine
description: |
    Flare is a a single-player 2D action RPG with fast-paced action and a dark fantasy style. It is
    built on the FLARE engine (Free/Libre Action Roleplaying Engine).

    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited
    using Tiled.
rundeps    :
    - flare-engine
setup      : |
    %cmake_ninja -DDATADIR="share/flare"
build      : |
    %ninja_build
install    : |
    %ninja_install
