name       : flare-game
version    : 1.02
release    : 4
source     :
    - https://github.com/clintbellanger/flare-game/archive/v1.02.tar.gz : d94996a9e3d9c1c95a71e9ad048ee717725c8ea29079e61a92e50773ca380241
license    :
    - GPL-3.0-or-later
    - CC-BY-SA-3.0
component  : games.rpg
summary    : Fantasy action RPG using the FLARE engine
description: |
    Flare is a a single-player 2D action RPG with fast-paced action and a dark fantasy style. It is
    built on the FLARE engine (Free/Libre Action Roleplaying Engine).

    Flare uses simple file formats (INI style config files) for most of the game data, allowing
    anyone to easily modify game contents. Open formats are preferred (png, ogg). Maps are edited
    using Tiled.
rundeps    :
    - flare-engine
setup      : |
    %cmake . -DDATADIR="share/flare"
install    : |
    %make_install
